learning_front:
    resource: "@LearningFrontBundle/Resources/config/routing.yml"
    prefix:   /

learning_user:
    resource: "@LearningUserBundle/Resources/config/routing.yml"
    prefix:   /

learning_admin:
    resource: "@LearningAdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

_imagine:
    resource: .
    type:     imagine